export const CURRENT_TAB_CHANGED = "CURRENT_TAB_CHANGED";
export const GET_DATA_FROM_DB = "GET_DATA_FROM_DB";
export const ADD_NEW_TRANSACTION = "ADD_NEW_TRANSACTION";
export const ADD_NEW_CATEGORY = "ADD_NEW_CATEGORY";
export const SET_SELECTED_ITEM = "SET_SELECTED_ITEM";
